### PR TITLE
Added support for merging PDFs.

### PR DESCRIPTION
**Pull request by enboig**
This way you can add multiple input files and they will be merged in output file.

### CODE REVIEW

**Comment by DaanDeSmedt** [comment]
@enboig - thanks for the addition! 👍 


It would be fantastic in order to complete the PR, to foresee :

- [ ] `public function getInputFile() : string` - should also reflect the multiple files change
- [ ] add a test to ensure multiple files integrity
- [ ] update [README.md](https://github.com/DaanDeSmedt/PHPGhostscript/blob/master/README.md) to reflect files list (merge)

**Comment by enboig** [comment]
How are tests run?
I tried 
```
$ phpunit tests/PHPGhostscript/PHPGhostscriptTest.php 
PHP Fatal error:  PHPUnit\TextUI\RuntimeException cannot implement PHPUnit\TextUI\Exception - it is not an interface in /usr/share/php/PHPUnit/TextUI/Exception/RuntimeException.php on line 15
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpunit:0
PHP   2. PHPUnit\TextUI\Command::main($exit = *uninitialized*) /usr/bin/phpunit:73
PHP   3. {closure:/usr/share/php/PHPUnit/Autoload.php:32-389}($class = 'PHPUnit\\TextUI\\RuntimeException') /usr/share/php/PHPUnit/TextUI/Command.php:98
PHP   4. require() /usr/share/php/PHPUnit/Autoload.php:387

```

**Comment by DaanDeSmedt** [comment]
From within the PHPGhostscript package directory (where the composer.json is located) you can use most basic command `phpunit`.

The PHPUnit configuration is stored in the [phpunit.xml](https://github.com/DaanDeSmedt/PHPGhostscript/blob/master/phpunit.xml) file.


Fore more in-depths, have a look at :

- [how-to-use-phpunit-installed-from-composer](https://stackoverflow.com/questions/13764309/how-to-use-phpunit-installed-from-composer)
- [how-create-php-package-part-2-phpunit)](https://demyanov.dev/how-create-php-package-part-2-phpunit)
- [phpunit-8](https://phpunit.de/getting-started/phpunit-8.html)

**Comment by enboig** [comment]
Done, I had some problems with gs path (I am using linux).

I changed tests to work on my environment, and undid them before commiting.

**Comment by enboig** [comment]
I was reticent to change  `getInputFile()` to  `getInputFiles()` for backward compatibility; but as soon as it change return type from string to array it was broken.

Thanks for committing the change.

**Comment by DaanDeSmedt** [comment]
I've merged and release a `1.1` version including your contributions - and mitigate the `getInputFiles()` change. 

Since the filelist is now a collection, it didn't make much sense to keep compatibility but not respecting the return as a collection. 


Thanks for the merge feature 👍!

**Pull request merged**
