### PR TITLE
Support for empty page range.

### PR DESCRIPTION
**Pull request by enboig**
Start page and end page was set initially to 1. I made this optional so merging documents with multiple pages (test provided) work correctly.

### CODE REVIEW

**Comment by enboig** [comment]
Maybe a unit test counting pages with:
```
gs -dNOSAFER -q -dNODISPLAY -c "(./merge2.pdf) (r) file runpdfbegin pdfpagecount = quit"
```
would make a good addition

**Comment by DaanDeSmedt** [comment]
Great, nice addition!
Almost there I think ...


The PR removes changes done to `public function getInputFile() : array` from [previous commit](https://github.com/DaanDeSmedt/PHPGhostscript/pull/3/files#diff-9d76c30053786c5d7601cdb3d0f87a910632296cf3cc40072af1228e96e64a27R345).

@enboig 
would you mind getting this re-fixed? 
Also the counting page approach would make sense to safe-guard amount of pages, would be nice to see that in a PR.

**Comment by enboig** [comment]
I thought having my repo synched with yours would be enought

**Comment by DaanDeSmedt** [comment]
> I thought having my repo synched with yours would be enought

Your branch, on which the PR changes had been done, is behind master. You can indeed sync the out-of-date branch and submit changes to this PR.

**Pull request closed without merging**
